#pragma kernel Draw

#define THREAD_X 32
#define THREAD_Y 32
#define THREAD_Z 1

RWTexture2D<float4> solver;
RWTexture2D<float> density;
RWTexture2D<float2> velocity;

// 描画処理
[numthreads(THREAD_X, THREAD_Y, THREAD_Z)]
void Draw(uint2 id : SV_DispatchThreadID)
{
    uint w, h;
    solver.GetDimensions(w, h);

    if (id.x < w && id.y < h)
    {
        solver[id] = float4(velocity[id].xy, density[id], 1);
    }
}
